//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biblioteca.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autor não foi encontrado!.
        /// </summary>
        public static string AUTHOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUTHOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autor não pode ser deletado pois está sendo referenciado!.
        /// </summary>
        public static string AUTHOR_WITH_REFERENCE {
            get {
                return ResourceManager.GetString("AUTHOR_WITH_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O livro não foi encontrado!.
        /// </summary>
        public static string BOOK_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOOK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve ter entre 1 e 20 caracteres!.
        /// </summary>
        public static string DESCRIPTION_RANGE {
            get {
                return ResourceManager.GetString("DESCRIPTION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória!.
        /// </summary>
        public static string DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A edição deve ser entre 1 e 9999!.
        /// </summary>
        public static string EDITION_RANGE {
            get {
                return ResourceManager.GetString("EDITION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido!.
        /// </summary>
        public static string INVALID_ID {
            get {
                return ResourceManager.GetString("INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço não pode ser maior que 9999999999999999!.
        /// </summary>
        public static string INVALID_PRICE {
            get {
                return ResourceManager.GetString("INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de autores deve ter pelo menos um elemento!.
        /// </summary>
        public static string LIST_AUTHOR_REQUIRED {
            get {
                return ResourceManager.GetString("LIST_AUTHOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de assuntos deve ter pelo menos um elemento!.
        /// </summary>
        public static string LIST_SUBJECT_REQUIRED {
            get {
                return ResourceManager.GetString("LIST_SUBJECT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter entre 1 e 40 caracteres!.
        /// </summary>
        public static string NAME_RANGE {
            get {
                return ResourceManager.GetString("NAME_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório!.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano de publicação deve começar com um caracter maior que zero e conter 4 digitos!.
        /// </summary>
        public static string PUBLICATION_YEAR_MATCH {
            get {
                return ResourceManager.GetString("PUBLICATION_YEAR_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A editora deve ter entre 1 e 40 caracteres!.
        /// </summary>
        public static string PUBLISHER_RANGE {
            get {
                return ResourceManager.GetString("PUBLISHER_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A editora é obrigatória!.
        /// </summary>
        public static string PUBLISHER_REQUIRED {
            get {
                return ResourceManager.GetString("PUBLISHER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O assunto não foi encontrado!.
        /// </summary>
        public static string SUBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O assunto não pode ser deletado pois está sendo referenciado!.
        /// </summary>
        public static string SUBJECT_WITH_REFERENCE {
            get {
                return ResourceManager.GetString("SUBJECT_WITH_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título deve ter entre 1 e 40 caracteres!.
        /// </summary>
        public static string TITLE_RANGE {
            get {
                return ResourceManager.GetString("TITLE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título é obrigatório!.
        /// </summary>
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
